variables:
  IMAGE: $DOCKER_USER/$CI_PROJECT_NAME

  SPIGOT_PROJECT_ID: 54
  SPIGOT_VERSION: "1.15.1"

  MAVEN_OPTS: "-Dhttps.protocols=TLSv1.2 -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true -XX:+TieredCompilation -XX:TieredStopAtLevel=1 -Djansi.force=true -Dmaven.repo.local=.m2/repository"
  MAVEN_CLI_OPTS: "--errors --fail-at-end --show-version -Dstyle.color=always"

cache:
  paths:
    - .m2/repository

##################################
## PRE
##################################

get-version:
  stage: .pre
  tags:
    - shell
  script:
    - ci/scripts/version.sh
  artifacts:
    reports:
      dotenv: build.env

clean-snapshot-version:
  stage: .pre
  tags:
    - shell
  script:
    - ci/scripts/clean-snapshot-version.sh ${CI_PROJECT_ID} ${API_TOKEN} ${VERSION} ${CI_API_V4_URL}
  needs:
    - job: get-version
      artifacts: true
  except:
    refs:
      - master
      - tags

##################################
## BUILD
##################################

include:
  - local: "ci/pipelines/builds.gitlab-ci.yml"
  - local: "ci/pipelines/merge-requests.gitlab-ci.yml"

##################################
## DEPLOY
##################################

deploy-botte:
  stage: deploy
  variables:
    PLAYBOOK_NAME: install_loup_garou.yml
    ENVIROMENT: inventory
    VARIABLES: "lg_container_version=$VERSION"
  trigger:
    project: nananas/ansible
    branch: master
    strategy: depend
  needs:
    - job: build-image
    - job: get-version
      artifacts: true
  except:
    - merge_requests

##################################
## WORKFLOW
##################################

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == 'web' || $CI_PIPELINE_SOURCE == 'merge_request_event'
      when: always
    - when: never
