variables:
  SPIGOT_PROJECT_ID: 54
  SPIGOT_VERSION:
    value: "1.15.1"
    description: "Spigot version"
  PACKAGES_PATH: "spigotmc"
  MAVEN_CLI_OPTS: "-s ci_settings.xml --errors --show-version -Dstyle.color=always"
  #MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"
#cache:
#  paths:
#    - .m2/repository/

stages:
  - build
  - upload

build:
  stage: build
  tags:
    - docker
  image: arm32v7/maven:3-jdk-8
  script:
    - rm -rf ~/.m2/repository
    - mvn deploy ${MAVEN_CLI_OPTS}
    #- 'curl -X GET --header "JOB-TOKEN: $CI_JOB_TOKEN" -k --output spigot.jar ${CI_API_V4_URL}/projects/${SPIGOT_PROJECT_ID}/packages/generic/${PACKAGES_PATH}/${SPIGOT_VERSION}/spigot.jar'
    #- mkdir lib
    #- mv spigot.jar lib/
    #- ls -la lib
    #- mvn clean $MAVEN_CLI_OPTS $MAVEN_OPTS deploy -DskipTests

#upload:
#  stage: upload
#  tags:
#    - shell
#    - localhost
#  script:
#    - 'curl --header "JOB-TOKEN: $CI_JOB_TOKEN" --upload-file maps/lg_medieval.zip "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/maps_medieval/1.0.0/lg_medieval.zip"'
#    - 'curl --header "JOB-TOKEN: $CI_JOB_TOKEN" --upload-file maps/lg_village.zip "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/maps_village/1.0.0/lg_village.zip"'
