variables:
  IMAGE: $DOCKER_USER/$CI_PROJECT_NAME

  SPIGOT_PROJECT_ID: 54
  SPIGOT_VERSION: '1.15.1'
  
  MAVEN_OPTS: '-Dhttps.protocols=TLSv1.2 -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true -XX:+TieredCompilation -XX:TieredStopAtLevel=1 -Djansi.force=true'
  MAVEN_CLI_OPTS: '--errors --fail-at-end --show-version -Dstyle.color=always'


##################################
## PRE
##################################

get-version:
  stage: .pre
  tags:
    - shell
  script:
    - ci/version.sh
  artifacts:
    reports:
      dotenv: build.env

clean-snapshot-version:
  stage: .pre
  tags:
    - shell
  script:
    - ci/clean-snapshot-version.sh ${CI_PROJECT_ID} ${API_TOKEN} ${VERSION} ${CI_API_V4_URL}
  needs:
    - job: get-version
      artifacts: true
  except:
    refs:
      - master
      - tags


##################################
## BUILD
##################################

include:
  - local: 'ci/pipeline/builds.gitlab-ci.yml'
  - local: 'ci/pipeline/merge-requests.gitlab-ci.yml'


##################################
## WORKFLOW
##################################

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == 'web' || $CI_PIPELINE_SOURCE == 'merge_request_event'
      when: always
    - when: never
