version: '3.0'

services:
  loup-garou:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        EULA: 'true'
        SPIGOT_VERSION: '1.15.1'
        VERSION: '1.2.0-SNAPSHOT'
    container_name: loup-garou
    ports:
      - 25560:25560
