name: LoupGarou
version: '${project.version}'
main: fr.leomelki.loupgarou.LoupGarou
api-version: 1.15
depend: [ ProtocolLib ]
authors: [ leomelki, PapierPain ]
description: Plugin Spigot LoupGarou
website: https://gitlab.papierpain.fr/minecraft/plugin-loup-garou

commands:
  lg:
    description: Manage LoupGarou game.
    usage: Type /lg to manage game.
