build-plugin:
  stage: build
  tags:
    - docker
  image: papierpain/maven-spigot:${SPIGOT_VERSION}
  script:
    - ci/build.sh "$MAVEN_CLI_OPTS"
  except:
    - merge_requests

build-image:
  stage: build
  tags:
    - shell
  before_script:
    - docker login docker.io -u $DOCKER_USER -p $DOCKER_TOKEN
  script:
    - |
      docker build \
        -t $IMAGE:$VERSION \
        -t $IMAGE:latest \
        --build-arg CI_API_V4_URL=$CI_API_V4_URL \
        --build-arg CI_PROJECT_ID=$CI_PROJECT_ID \
        --build-arg PACKAGES_PATH=$PACKAGES_PATH \
        --build-arg SPIGOT_PROJECT_ID=$SPIGOT_PROJECT_ID \
        --build-arg SPIGOT_VERSION=$SPIGOT_VERSION \
        --build-arg API_TOKEN=$API_TOKEN \
        --build-arg VERSION=$VERSION \
        -f ci/Dockerfile.prod .
    - docker push $IMAGE:$VERSION
    - docker push $IMAGE:latest
  after_script:
    - docker logout
    - docker images --format "{{.Repository}}:{{.Tag}}:{{.ID}}" | grep "$IMAGE" | cut -f 3 -d ":" | xargs docker rmi
  needs:
    - job: get-version
      artifacts: true
    - job: build-plugin
  except:
    - merge_requests
